In [2]:
# TO DO: CREATE A NEW MULTI-LEVEL DATAFRAME FORMATTED LIKE THAT IN 05-APIs/3/Activities/06-Stu_Financial_Forecasting/Solved (YONATHAN AND SAM)
# TO DO: THE INDEX SHOULD BE A DATETIME AND IT SHOULD BE A DATETIME FORMAT (NOT A STRING)
# TO DO: THE 1ST LEVEL SHOULD BE THE COIN SYMBOL (FOR EXAMPLE: TSLA -> USDC... AND THEN ANOTHER SECTION FOR DAI etc..)
# TO DO: THE 2ND LEVEL SHOULD CONTAIN 'close' and 'daily_return'
# TO DO: 'daily_return' SHOULD EQUAL pct_change IN PRICE FOR THAT COIN + WHAT OUR FUNCTION RETURNS BY FEEDING IN THE DEPOSIT RATE FOR A DAY AS THE APY PARAMETER
# TO DO: THIS DATA WILL GET PULLED BY USING A FOR LOOP TO ITERATE THROUGH editing_dataframe
## ['USDC', 'DAI', 'USDT', 'WETH', 'WBTC', 'AAVE', 'WMATIC' ]:
import requests
import json
import pandas as pd
from datetime import datetime, timedelta
import time
import csv
# %%
base_url = 'https://aave-api-v2.aave.com/data/liquidity/v2?poolId=' # This is the base API URL
pool_id = '0xd05e3e715d945b59290df0ae8ef85c1bdb684744' # This is the Pool ID for the Matic Network
# %%
range_of_dates = pd.date_range(start = "2021-04-01",end = (datetime.today() - timedelta(days = 1))).date # List of dates from the start of the AAVE API to yesterday
list_of_dates = []
for date in range_of_dates: # For each date in the list of dates
    list_of_dates.append(date.strftime("%m-%d-%Y")) # Format it correctly for use in the API and append it to a new list
# %%
col_names = ['Date','Symbol', 'USD', 'priceInETH', 'Deposit Rate', 'aIncentivesAPY',
             'vIncentivesAPY','totalLiquidity','utilizationRate','vEmissionPerSecond','totalVariableDebt',
             'lifetimeDepositorsInterestEarned','availableLiquidity','aEmissionPerSecond','totalLiquidityNormalized',
             'totalBorrowsNormalized','totalBorrowsVariableNormalized', 'availableLiquidityNormalized'] 
# These are the fields we want

## totalLiquidity X 
## utilizationRate X
## vEmissionPerSecond X
## totalVariableDebt X
## lifetimeDepositorsInterestEarned X
## availableLiquidity X
## aIncentivesAPY X
## vIncentivesAPY X
## priceInUsd X
## aEmissionPerSecond X
## totalLiquidityNormalized X
## totalBorrowsNormalized X
## totalBorrowsVariableNormalized X
## availableLiquidityNormalized X

matic_dataframeWETH = pd.DataFrame(columns = col_names) # Create an empty DataFrame with the column headers
# %%
for date in list_of_dates: # For each date in the list
    print(date) # Show progress as the API is runnin
    request_url = base_url + pool_id + '&date=' + date # Build the Request URL by combining the base, poolID we want, and one date out of the list of dates
    response_data = requests.get(request_url).json() # Make the request and return the data
    while isinstance(response_data, dict) == True: # If we get an error back
        print(json.dumps(response_data, indent=4)) # Dump the error
        time.sleep(5) # Wait 5 seconds to get around rate limiting
        response_data = requests.get(request_url).json() # Try again
    for response in response_data: # For each element in the response
        if response['symbol'] in ['WETH']: # 
            dict_to_append = { # Set the values of the row we want to append to the DataFrame
                'Date' : date, # Date is the date we queried for
                'Symbol' : response['symbol'], # Set symbol in the row to the symbol the API returns
                'Price in ETH': response['price']['priceInEth'], #price in the row to the price in Eth the API returns
                'Deposit Rate': response['liquidityRate'], # Set deposit rate to the deposit rate the API returns
                'aIncentivesAPY' : response['aIncentivesAPY'],# Set deposit rewards to the rate the API returns
                'vIncentivesAPY' : response['vIncentivesAPY'],
                'totalLiquidity' : response['totalLiquidity'],
                'utilizationRate' : response['utilizationRate'],
                'vEmissionPerSecond' : response['vEmissionPerSecond'],
                'totalVariableDebt' : response['totalVariableDebt'],
                'lifetimeDepositorsInterestEarned' : response['lifetimeDepositorsInterestEarned'],
                'availableLiquidity' : response['availableLiquidity'],
                'aEmissionPerSecond' : response['aEmissionPerSecond'],
                'totalLiquidityNormalized' : response['totalLiquidityNormalized'],
                'totalBorrowsNormalized' : response['totalBorrowsNormalized'],
                'totalBorrowsVariableNormalized' : response['totalBorrowsVariableNormalized'],
                'availableLiquidityNormalized' : response['availableLiquidityNormalized'],  
                'USD' : response['referenceItem']['priceInUsd'],  
            }
             
            matic_dataframeWETH = matic_dataframeWETH.append(dict_to_append, ignore_index = True) # Append the row to the DataFrame
# %%
#--------Once you've imported the data, only ever run from this cell downwards---------

# %%

editing_dataframeWETH = matic_dataframeWETH # Resets the dataframe to the one imported, that way you don't have to rerun the import everytime. Placeholder until Thomas gets the csv writeout completed.
editing_dataframeWETH.head() # Use editing_dataframe as your reference dataframe moving forward until the CSV writing gets completedv


matic_dataframeWETH.head()
matic_dataframeWETH.tail()

04-01-2021
04-02-2021
04-03-2021
04-04-2021
04-05-2021
04-06-2021
04-07-2021
04-08-2021
04-09-2021
04-10-2021
04-11-2021
04-12-2021
04-13-2021
04-14-2021
04-15-2021
04-16-2021
04-17-2021
04-18-2021
04-19-2021
04-20-2021
04-21-2021
04-22-2021
04-23-2021
04-24-2021
04-25-2021
04-26-2021
04-27-2021
04-28-2021
04-29-2021
04-30-2021
05-01-2021
05-02-2021
05-03-2021
05-04-2021
05-05-2021
05-06-2021
05-07-2021
05-08-2021
05-09-2021
05-10-2021
05-11-2021
05-12-2021
05-13-2021
05-14-2021
05-15-2021
05-16-2021
05-17-2021
05-18-2021
05-19-2021
05-20-2021
05-21-2021
05-22-2021
05-23-2021
05-24-2021
05-25-2021
05-26-2021
05-27-2021
05-28-2021
05-29-2021
05-30-2021
05-31-2021

,Date,Symbol,USD,priceInETH,Deposit Rate,aIncentivesAPY,vIncentivesAPY,totalLiquidity,utilizationRate,vEmissionPerSecond,totalVariableDebt,lifetimeDepositorsInterestEarned,availableLiquidity,aEmissionPerSecond,totalLiquidityNormalized,totalBorrowsNormalized,totalBorrowsVariableNormalized,availableLiquidityNormalized,Price in ETH
56,05-27-2021,WETH,2741.373786630001725184918209414994,NaN,0.01383649282164498404,0.0206306704440384082,0.05837731075984042347,800286.79413980070390086,0.35340220670512440189,706597222222222222,282823.119045975188213867,566459774256573921683,517463.675093825515686993,706597222222222222,799652.112708312070991104,2766809.678531097118768638,2766809.678531097118768638,517463.669662260343093188,1
57,05-28-2021,WETH,2417.975942620000504881368761501172,NaN,0.01443929738889622653,0.01983250370715320373,0.05493657320989479074,813129.45631992396954421,0.36100729529269423176,706597222222222222,293545.665748874708387146,608118256886897169999,519583.790571049261157064,706597222222222222,809470.649337766339210795,3135268.754578192107874952,3135268.754578192107874952,517878.417402935214190083,1
58,05-29-2021,WETH,2276.347807650004222020106383284652,NaN,0.01410135969237275665,0.0202162167829486014,0.05666601420642897629,831016.144654824468339062,0.35676087450412198217,706597222222222222,296474.046494099111696182,635876301552887087329,534542.09816072535664288,706597222222222222,811477.686198686738107853,3605850.005651778340483875,3605850.005651778340483875,517795.330822462350901855,1
59,05-30-2021,WETH,2386.218048650004303241001202342636,NaN,0.01371448542782849034,0.01996819733041506513,0.05675426887536392234,858490.325458120390072518,0.35183604204763045024,706597222222222222,302047.838245367195532933,663363556453076302718,556442.487212753194539585,706597222222222222,851201.81703432954238197,4131804.233856589102096663,4131804.233856589102096663,554418.614885578309821802,1
60,05-31-2021,WETH,2707.864218640006372258598210709025,NaN,0.01449768643791884075,0.0173749174133163574,0.04803088704515634507,892700.020969115773055778,0.36174467061125250974,706597222222222222,322929.475040130993774032,695315233185156390869,569770.545928984779281746,706597222222222222,891950.741388990887311423,5171930.996176593540660964,5171930.996176593540660964,569800.631172095280591145,1